language: nodejs

services:
  - docker

build:
- docker-compose -f docker-compose-build.yaml build --parallel

login:
- echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin

tag:
- docker tag udagram-api-feed "$USERNAME/udagram-api-feed:v1.0.0"
- docker tag udagram-api-user "$USERNAME/udagram-api-user:v1.0.0"
- docker tag udagram-frontend "$USERNAME/udagram-frontend:v1.0.0"
- docker tag reverseproxy "$USERNAME/reverseproxy:v1.0.0"

push:
- docker-compose -f docker-compose-push.yaml push