language: nodejs

services:
  - docker

build:
- docker-compose -f docker-compose-build.yaml build --parallel

login:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

tag:
- docker tag udagram-api-feed ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v1.0.0
- docker tag udagram-api-user ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v1.0.0
- docker tag udagram-frontend ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v1.0.0
- docker tag reverseproxy ${{ secrets.DOCKER_USERNAME }}/reverseproxy:v1.0.0

push:
- docker-compose -f docker-compose-push.yaml push