version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: $USERNAME/reverseproxy:v1.0.0
  backend_user:
    build:
      context: ./udagram-api-user
    image: $USERNAME/udagram-api-user:v1.0.0
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: $USERNAME/udagram-api-feed:v1.0.0
  frontend:
    build:
      context: ./udagram-frontend
    image: $USERNAME/udagram-frontend:v1.0.0
