apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: jimohar/udagram-api-feed:v1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mysecret
            - configMapRef:
                name: config-secret
