name: Docker Image Push CI

on: workflow_dispatch
  # push:
  #   branches: [ "main", "dev" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: |
          docker-compose -f docker-compose-build.yaml build --parallel
          
    - name: Login to DockerHub
      run: echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      
    - name: Tag the Docker images to the Registry
	  run: |
		  docker tag udagram-api-feed "$USERNAME/udagram-api-feed:v1.0.0"
		  docker tag udagram-api-user "$USERNAME/udagram-api-user:v1.0.0"
		  docker tag udagram-frontend "$USERNAME/udagram-frontend:v1.0.0"
		  docker tag reverseproxy "$USERNAME/reverseproxy:v1.0.0"
	
	- name: Push to DockerHub Registry
	  run: |
		  docker-compose -f docker-compose-push.yaml push