name: Docker Image Push CI
on:
	workflow_dispatch:
  # push:
  #   branches: [ "main", "dev" ]
  # pull_request:
  #   branches: [ "main" ]
env:
	USERNAME: ${{ secrets.DOCKER_USERNAME }}
	PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
	build:
		runs-on: ubuntu-latest
		steps:
		- name: Build the Docker images
		run: |
		docker-compose -f docker-compose-build.yaml build --parallel

		- name: Login to DockerHub
		run: echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
	
		- name: Tag the Docker images to the Registry
		run: |
		docker tag udagram-api-feed "$USERNAME/udagram-api-feed"
		docker tag udagram-api-user "$USERNAME/udagram-api-user"
		docker tag udagram-frontend "$USERNAME/udagram-frontend"
		docker tag reverseproxy "$USERNAME/reverseproxy"
	
		- name: Push to DockerHub Registry
		run: docker-compose -f docker-compose-push.yaml push
